### ISSUE TITLE
Protection level A and B in yaml

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#24]
If you analyse

[trt.eti.zip](https://github.com/Opendigitalradio/etisnoop/files/2449556/trt.eti.zip)

with

`etisnoop -i trt.eti -v -s trt.yaml`

the output shows both protection levels, A and (!) B. It's A only according to other tools.

```
more /tmp/trt.yaml 
# Statistics from ETISnoop. This file should be valid YAML
---
ensemble:
    id: 0x4fff
    label: TRT DAB+        
    shortlabel: DAB+
audio:
    - service_id: 0x32
      subchannel_id: 0xb
      label: +Radyo 1        
      shortlabel: +Radyo 1
      subchannel:
          id: 11
          SAd: 0
          protection: EEP 4-A
          protection: EEP 4-B
          protection: unknown
          size: 48
```
