### ISSUE TITLE
Missing Labels in yaml-file for data stream

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#25]
Today DAB Italia started a data package called "Cisco test" nationwide, so I found out that the yaml file does not mention the short and long label for this type of streams.

http://www.digitalbitrate.com/dtv.php?brk=2&mux=12C&pid=80&live=171&sec=0&lang=fr

[12c_italia_cisco.eti.zip](https://github.com/Opendigitalradio/etisnoop/files/3623443/12c_italia_cisco.eti.zip)

[12c.yaml.txt](https://github.com/Opendigitalradio/etisnoop/files/3623437/12c.yaml.txt)

```
    - service_id: 0x0
      subchannel_id: 0x16
      label: 
      shortlabel: 
      subchannel:
          id: 22
          SAd: 172
          protection: EEP 3-A
          size: 180
      audio:
          average: -90 -90
          peak: -90 -90
```

```
$ etisnoop -i /media/andreas/Data/dab/12c_italia_cisco.eti -n 100 | grep Cisco -A 1 -B 6
Identified ETI type RAW
ERRORS: Not yet in DB
ERRORS: Not yet in DB
ERRORS: Not yet in DB
     FIG: 1/5
     Length: 23
     OE: 0
     Decoding:
      Charset: 0
      Service ID: 0xE0500000
      Label: "Cisco Test      "
      Short label mask: 0xFE00
--
     FIG: 1/5
     Length: 23
     OE: 0
     Decoding:
      Charset: 0
      Service ID: 0xE0500000
      Label: "Cisco Test      "
      Short label mask: 0xFE00
Decoded 100 ETI frames
```
